port: 2333

server:
  catSpeed: 0.4
  mouseSpeed: 0.4
  roundLengthSec: 180
  cooldownTimeSec: 5
  # Allows player 0 to be a cat and a mouse - can kill other mice, hold item,
  # see everything on the minimap
  player0DevMode: false



client:
  # ONLY UNCOMMENT/SET IPADDR IF YOU'RE USING A SEPARATE MACHINE!
  # FOR SAME MACHINE SERVER/CLIENT LEAVE IT COMMENTED OUT
  # ipAddr: 128.54.70.30