port: 2333

server:
  playerSpeed: 0.4
  roundLengthSec: 180
  cooldownTimeSec: 5


client:
  # ONLY UNCOMMENT/SET IPADDR IF YOU'RE USING A SEPARATE MACHINE!
  # FOR SAME MACHINE SERVER/CLIENT LEAVE IT COMMENTED OUT
  # ipAddr: ""
